version: '3.8'

services:
  study-helper:
    image: doge2mars/study-helper:latest
    container_name: study-helper-pro
    ports:
      - "8866:8000"
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
    restart: always
    environment:
      - TZ=Asia/Shanghai
